# Site settings
author: Paulette Rousselle
title: Musings in Data Science
header-img: img/home-bg.png
email: pauletterous@gmail.com
copyright_name: Paulette Rousselle
description: > # this means to ignore newlines until "baseurl:"
  A journey of pondering all aspects of the field of data science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  PauletteJ

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
